# This file was generated by GoReleaser. DO NOT EDIT.
class GitProfileManager < Formula
  desc "Allows to manage and switch between multiple git profiles"
  homepage "https://github.com/Dm3Ch/git-profile-manager"
  version "2.0.3"

  if OS.mac?
    url "https://github.com/dm3ch/git-profile-manager/releases/download/v2.0.3/git-profile-manager_2.0.3_MacOS_x86_64.tar.gz"
    sha256 "92ec7c312dbfdb8b19a96dbaf764f1454ae293c10a4fa27e38b5b832d7120ea4"
  elsif OS.linux?
    url "https://github.com/dm3ch/git-profile-manager/releases/download/v2.0.3/git-profile-manager_2.0.3_Linux_x86_64.tar.gz"
    sha256 "232f749e815c8f19178fa6febe84887816c04d0bccc99a83e7189d70f3ecd331"
  end
  
  head "https://github.com/Dm3Ch/git-profile-manager.git"
  
  depends_on "git"

  def install
    ln_s "git-profile-manager", "git-profile"
    bin.install "git-profile-manager"
    bin.install "git-profile"
    
    system "#{bin}/git-profile-manager completion bash > bash_completion.bash"
    system "#{bin}/git-profile-manager completion zsh > zsh_completion.zsh"
    bash_completion.install "bash_completion.bash"
    zsh_completion.install "zsh_completion.zsh"
  end

  def caveats; <<~EOS
    git-profile-manager --help
  EOS
  end

  test do
    system "#{bin}/git-profile-manager", "--version"
  end
end
