# This file was generated by GoReleaser. DO NOT EDIT.
class GitProfileManager < Formula
  desc "Allows to manage and switch between multiple git profiles"
  homepage "https://github.com/Dm3Ch/git-profile-manager"
  version "2.0.2"

  if OS.mac?
    url "https://github.com/Dm3Ch/git-profile-manager/releases/download/v2.0.2/git-profile-manager_2.0.2_MacOS_x86_64.tar.gz"
    sha256 "cbc672141d0e3ed184120db3efdb2f9c79ceadcb5b120cf18071470377362e2e"
  elsif OS.linux?
    url "https://github.com/Dm3Ch/git-profile-manager/releases/download/v2.0.2/git-profile-manager_2.0.2_Linux_x86_64.tar.gz"
    sha256 "2d5459378151b576162729392163233a60ac365d91942b3dda66d734c62cc8c6"
  end
  
  head "https://github.com/Dm3Ch/git-profile-manager.git"
  
  depends_on "git"

  def install
    ln_s "git-profile-manager", "git-profile"
    bin.install "git-profile-manager"
    bin.install "git-profile"
    
    system "#{bin}/git-profile-manager completion bash > bash_completion.bash"
    system "#{bin}/git-profile-manager completion zsh > zsh_completion.zsh"
    bash_completion.install "bash_completion.bash"
    zsh_completion.install "zsh_completion.zsh"
  end

  def caveats; <<~EOS
    git-profile-manager --help
  EOS
  end

  test do
    system "#{bin}/git-profile-manager", "--version"
  end
end
